spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa1
    username: root
    password: 419914

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

server:
  servlet:
    session:
      cookie:
        http-only: false